

create TABLE NHANVIEN
(
    MANV varchar2(5),
    HOTEN NVARCHAR2(50),
    GIOITINH NVARCHAR2(5),
    NGAYSINH DATE,
    DIACHI NVARCHAR2(100),
    LUONG NUMBER,
    VAITRO NVARCHAR2(50),
    DONVI NUMBER,
    PRIMARY KEY(MANV)
);

CREATE TABLE DONVI
(
    MADV NUMBER,
    TENDV NVARCHAR2(50),
    PRIMARY KEY(MADV)
);


CREATE TABLE BENHNHAN
(
    MABN NUMBER,
    HOTEN NVARCHAR2(50),
    NGAYSINH DATE,
    DIACHI VARCHAR2(50),
    SODT CHAR(10),
    PRIMARY KEY(MABN)
);

CREATE TABLE HOSOBENHNHAN
(
    MAKB NUMBER,
    NGAYKB DATE,
    MATT varchar2(5),
    MABS varchar2(5),
    MABN varchar2(5),
    TINHTRANGBANDAU NVARCHAR2(200),
    KETLUANCUABS NVARCHAR2(200),
    PRIMARY KEY(MAKB)
);


CREATE TABLE HOSODICHVU
(
    MAKB NUMBER,
    MADV NUMBER,
    NGAYGIO DATE,
    NGUOITHUCHIEN varchar2(5),
    KETLUAN NVARCHAR2(200),
    PRIMARY KEY (MAKB,MADV)
);

CREATE TABLE DICHVU
(
    MADV NUMBER,
    TENDV NVARCHAR2(50),
    DONGIA NUMBER,
    PRIMARY KEY(MADV)
);
CREATE TABLE DONTHUOC
(
    MAKB NUMBER,
    NVPT varchar2(5),
    PRIMARY KEY(MAKB)
);

CREATE TABLE CHITIETDONTHUOC
(
    MAKB NUMBER,
    MATHUOC NUMBER,
    SL NUMBER,
    LIEUDUNG NUMBER,
    MOTA NVARCHAR2(50),
    PRIMARY KEY(MAKB, MATHUOC)
);

CREATE TABLE THUOC
(
    MATHUOC NUMBER,
    TENTHUOC NVARCHAR2(50),
    DVT VARCHAR2(50),
    DONGIA NUMBER,
    LUUY NVARCHAR2(50),
    PRIMARY KEY(MATHUOC)
);

CREATE TABLE HOADON
(
    SOHD NUMBER,
    MAKB NUMBER,
    NGAYHD DATE,
    NGUOIPT varchar2(5),
    TONGTIEN NUMBER,
    PRIMARY KEY(SOHD)
);

CREATE TABLE CTHDON
(
    SOHD NUMBER,
    MADV NUMBER,
    PRIMARY KEY(SOHD, MADV)
);

CREATE TABLE CHAMCONG
(
    MANV varchar2(5),
    SONGAYCONG NUMBER,
    ID_THANGNAM NUMBER,
    PRIMARY KEY(MANV,ID_THANGNAM)
);


CREATE TABLE THANGNAM
(
    ID_THANGNAM NUMBER,
    THANG NUMBER,
    NAM NUMBER,
    PRIMARY KEY(ID_THANGNAM)
);



ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_DONVI FOREIGN KEY(DONVI) REFERENCES DONVI(MADV);

ALTER TABLE HOSOBENHNHAN ADD CONSTRAINT FK_HSBN_BN FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN);

ALTER TABLE HOSOBENHNHAN ADD CONSTRAINT FK_HSBN_NV1 FOREIGN KEY(MATT) REFERENCES NHANVIEN(MANV);

ALTER TABLE HOSOBENHNHAN ADD CONSTRAINT FK_HSBN_NV2 FOREIGN KEY(MABS) REFERENCES NHANVIEN(MANV);

ALTER TABLE HOSODICHVU ADD CONSTRAINT FK_HSDV_HSBN FOREIGN KEY(MAKB) REFERENCES HOSOBENHNHAN(MAKB);

ALTER TABLE HOSODICHVU ADD CONSTRAINT FK_HSDV_DICHVU FOREIGN KEY(MADV) REFERENCES DICHVU(MADV);

ALTER TABLE HOSODICHVU ADD CONSTRAINT FK_HSDV_NHANVIEN FOREIGN KEY(NGUOITHUCHIIEN) REFERENCES NHANVIEN(MANV);

ALTER TABLE DONTHUOC ADD CONSTRAINT FK_DONTHUOC_NHANVIEN FOREIGN KEY(NVPT) REFERENCES NHANVIEN(MANV);

ALTER TABLE CHITIETDONTHUOC ADD CONSTRAINT FK_CTDT_HSBN FOREIGN KEY(MAKB) REFERENCES HOSOBENHNHAN(MAKB);

ALTER TABLE CHITIETDONTHUOC ADD CONSTRAINT FK_HSDV_THUOC FOREIGN KEY(MATHUOC) REFERENCES THUOC(MATHUOC);

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_HSBN FOREIGN KEY(MAKB) REFERENCES HOSOBENHNHAN(MAKB);

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(NGUOIPT) REFERENCES NHANVIEN(MANV);

ALTER TABLE CTHDON ADD CONSTRAINT FK_CTHDON_HOADON FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD);

ALTER TABLE CTHDON ADD CONSTRAINT FK_CTHDON_DICHVU FOREIGN KEY(MADV) REFERENCES DICHVU(MADV);

ALTER TABLE CHAMCONG ADD CONSTRAINT FK_CHAMCONG_THANGNAM FOREIGN KEY(ID_THANGNAM) REFERENCES THANGNAM(ID_THANGNAM);

ALTER TABLE CHAMCONG ADD CONSTRAINT FK_CHAMCONG_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV);

